server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  #pipeline_stages:
    #- regex:
        #expression: "Length of input: (?P<length_of_input>\d+)"
    ## Need to setup prometheus for this
    #- metrics:
        #inputs_given:
          #type: Counter
          #description: "The number of inputs"
          #source: length_of_input
          #config:
            #action: add
  static_configs:
  - targets:
      - localhost
    labels:
      job: sample_tool_logs
      __path__: /logs/*.log*
